version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask_ml_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: html_web_ui
    ports:
      - "8080:80"
    depends_on:
      - backend